### ISSUE TITLE
blake3.createKeyed is not a function

### ISSUE THREAD

**Issue by qgustavor** [connor4312/blake3#10]
Test case (can be run in browser console):

```javascript
const blake3Loader = await import('https://unpkg.com/blake3@2.1.1/browser-async.js')
const blake3 = await blake3Loader.default()
const keyedHash = blake3.createKeyed(new Uint8Array(32))
```

Throws `TypeError: blake3.createKeyed is not a function`.

Seems that [in this commit](https://github.com/connor4312/blake3/commit/3bcfd0df5033e3f1740fb1d1f6d467c1ed2dac2e) `createKeyed` and `createDeriveKey` were added to [ts/node/hash-instance.ts](https://github.com/connor4312/blake3/commit/3bcfd0df5033e3f1740fb1d1f6d467c1ed2dac2e#diff-b976acde3a92631208b2cbf1a0b6ba23) but not to [ts/browser/hash-instance.ts](https://github.com/connor4312/blake3/blob/4fcef6cfdd36795a93627009becf30559216b86c/ts/browser/hash-instance.ts).

**Comment by connor4312** [comment]
Fixed in https://github.com/connor4312/blake3/commit/98ea3356936a8a537991aebad3c9e104314fbb07
