### ISSUE TITLE
nodejs importing wasm

### ISSUE THREAD

**Issue by boogerlad** [connor4312/blake3#22]
I noticed in `dist/index.js` it `__export(require("./node-native"));`
If I wanted wasm, I can `__export(require("./node"));`
What is the proper way to do this?

I would like to use the wasm version since the performance is much higher than neon for small inputs (16 bytes)

**Comment by boogerlad** [comment]
Feel free to close this. I realized I can just write a `postinstall` script to reverse `useNativeImport`

**Comment by connor4312** [comment]
I'd recommend in this case manually importing `blake3/dist/node`
