### ISSUE TITLE
Problem during using npm i

### ISSUE THREAD

**Issue by hakimehmordadi** [connor4312/blake3#40]
![Screenshot from 2022-02-07 16-59-12](https://user-images.githubusercontent.com/31950758/152802125-5702fcc6-cddb-4e8d-9c8e-7d8ea06277fb.png)
We Have package-lock.json file which includes many packages. During Npm i , we are getting this problem. 

```
API version for node@v12.22.7 linux not explicitly built, falling back to latest. If this does not work, open an issue at https://github.com/connor4312/blake3/issues/new
Retrieving native BLAKE3 bindings for Node v12 on linux...
```
npm i  was stooped in this line  `Retrieving native BLAKE3 bindings for Node v12 on linux...`  So we can not install packages because we should exit from npm i. 

Please let me know, why this is happening?
We can not install packageg and buil our projecy. We are blocked.

Please help. It is urgent need.

Node version is : v12.22.7

Thanks

**Comment by connor4312** [comment]
Please update to version 2.1.5 of this package.
