### ISSUE TITLE
Browser API depends on webpack

### ISSUE THREAD

**Issue by qgustavor** [connor4312/blake3#8]
I tried importing it using `const blake3 = await import('https://unpkg.com/blake3@2.0.0/browser.js?module')` and it failed with `Uncaught ReferenceError: exports is not defined`. Seems the code is a mix of ES modules and CommonJS modules.

I also tried importing it using [Parcel](https://parceljs.org/) and it failed with `Imports argument must be present and must be an object`. Checking [this issue](https://github.com/parcel-bundler/parcel/issues/647) seems Parcel's WASM importing behavior is different from webpack's. Then, after, I tried importing it using webpack, it worked.

Is there a way to make it not dependent on webpack behavior?

**Comment by connor4312** [comment]
Good issue. I didn't bother having an entirely separate, pure ES module tree here like I normally do because wasm is not tree shakable anyway. But I didn't recognize that that would trip up non-Webpack bundlers. Will make a patch release this evening or tomorrow.

**Comment by connor4312** [comment]
Should be good to go in 2.0.1. `./browser.js` now points to [an esm build](https://unpkg.com/blake3@2.0.1/esm/browser/index.js). Let me know if you run into any more problems, happy hashing.

**Comment by qgustavor** [comment]
I just want to note that making it a ESM build just makes it easier to be imported into browsers without requiring a bundler, in the other hand it don't solves the issue.

The issue is that [blake3_js.js](https://unpkg.com/browse/blake3@2.0.1/dist/wasm/browser/blake3_js.js) imports "blake3_js_bg.wasm" as a ES module and [it is not standardized yet](https://github.com/WebAssembly/proposals/issues/12), so browsers don't support it and each some bundlers handle it in different ways than Webpack.

"blake3_js.js" is generated using wasm-pack  and [seems it don't support Parcel](https://github.com/rustwasm/wasm-pack/issues/699#issuecomment-520732132). You can use `--target web`, which will create a module that already handles WASM loading without depending on the bundler implementation, but then you need to initialize the module manually.

**Comment by connor4312** [comment]
I'll look into this some more this evening most likely.

**Comment by connor4312** [comment]
I've fixed this in https://github.com/connor4312/blake3/commit/8c48e49f7747b86101c8eb79876d9daf9254ebc9.

There's now a new import, `blake3/browser-async`, that exports an function which returns a promise that resolves to the module.

```js
import load from 'blake3/brwoser-async';

load().then(blake3 => {
  console.log(blake3.hash('hello world'));
});
```

I expanded the integration tests to test both Webpack and a plain `<script type="module">` import.
