### ISSUE TITLE
Support derive key

### ISSUE THREAD

**Issue by okuryu** [connor4312/blake3#9]
This lib seems to not support the `derive_key` mode. Right?
https://github.com/BLAKE3-team/BLAKE3/tree/5ef22de9d055bc5d65c1e70734a9047842ed3ed1#the-blake3-crate

**Comment by connor4312** [comment]
Correct. That's under https://github.com/connor4312/blake3/issues/2, which I haven't had a chance to do yet. I'm planning to take care of it some time this week/end. PRs welcome as well.

**Comment by connor4312** [comment]
2.1.0 has this. Let me know if you hit issues.
